#!/bin/bash

# case：合并匹配模式
echo "Is it morning? Please answer yes or no"
read timeofday

case "$timeofday" in
yes | y | Yes | YES) echo "Good Morning";; # 
n*  | N* ) echo "Good Afternoon";; # *通配符
* ) echo "Sorry, answer not recognized";;
esac
exit 0
