#!/bin/sh

echo "Is it moring? Please answer yes or no"
read timeofday

if [ $timeofday = "yes" ]; then
echo "Good morning"
elif [ $timeofday = "no" ]; then # elif命令会在第一个if
echo "Good afternoon"
else
echo "Sorry, $timeofday not recognized. Enter yes or no"
fi

exit 0